name: video_caption
channels:
  - defaults
dependencies:
- python>=3.8,<3.11
- pip>=21
- scikit-image
- pip:
   - transformers~=4.10.2
   - opencv-python
   - ftfy
   - regex
   - tqdm
   - loguru
   - git+https://github.com/openai/CLIP.git